modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="energioom"
version="1.0.0"
displayName="Energioom"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="dommilosz"

[[dependencies.energioom]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




